---
Parameters:
  SGDesc:
    Description: Security Group Description
    Type: String


Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08bc77a2c7eb2b1da
      InstanceType: t2.micro
      Tags:
      - Key: Name
        Value: SysOps
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SGDesc
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
